import { Account } from "../models/Account";

export const seedAccounts = async () => {
    await Account.deleteMany();
    await Account.create([
        {
            name: "João Silva",
            email: "joao.silva@example.com",
            avatar: null,
            password: "123456",
            phone_number: "11999999999",
            role: "user",
            cpf: "12345678901",
            verified: true,
            address: {
                street: "Rua das Flores",
                number: "123",
                complement: "Apto 101",
                city: "São Paulo",
                cep: "01001000",
                state: "SP",
            },
        },
        {
            name: "Maria Oliveira",
            email: "maria.oliveira@example.com",
            avatar: null,
            password: "senhaSegura",
            phone_number: "21988887777",
            role: "user",
            cpf: "23456789012",
            verified: false,
            address: {
                street: "Avenida Brasil",
                number: "456",
                city: "Rio de Janeiro",
                cep: "20040002",
                state: "RJ",
            },
        },
        {
            name: "Carlos Souza",
            email: "carlos.souza@example.com",
            avatar: null,
            password: "abc123",
            phone_number: "31977776666",
            role: "admin",
            cpf: "34567890123",
            verified: true,
            address: {
                street: "Rua Minas Gerais",
                number: "789",
                city: "Belo Horizonte",
                cep: "30130010",
                state: "MG",
            },
        },
        {
            name: "Ana Pereira",
            email: "ana.pereira@example.com",
            avatar: null,
            password: "senha123",
            phone_number: "41966665555",
            role: "user",
            cpf: "45678901234",
            verified: false,
            address: {
                street: "Rua XV de Novembro",
                number: "321",
                city: "Curitiba",
                cep: "80020010",
                state: "PR",
            },
        },
        {
            name: "Instituto Esperança",
            email: "contato@institutoesperanca.org",
            avatar: null,
            password: "inst123",
            phone_number: "11955554444",
            role: "institution",
            cnpj: "12345678000199",
            verified: true,
            address: {
                street: "Rua Solidária",
                number: "50",
                city: "São Paulo",
                cep: "03010000",
                state: "SP",
            },
        },
        {
            name: "Pedro Gomes",
            email: "pedro.gomes@example.com",
            avatar: null,
            password: "pedro123",
            phone_number: "61944443333",
            role: "user",
            cpf: "56789012345",
            verified: true,
            address: {
                street: "Quadra 10",
                number: "20",
                city: "Brasília",
                cep: "70040900",
                state: "DF",
            },
        },
        {
            name: "Associação Vida Nova",
            email: "contato@vidanova.org",
            avatar: null,
            password: "vida123",
            phone_number: "11933332222",
            role: "institution",
            cnpj: "23456789000188",
            verified: false,
            address: {
                street: "Avenida Principal",
                number: "500",
                city: "Campinas",
                cep: "13010100",
                state: "SP",
            },
        },
        {
            name: "Lucas Fernandes",
            email: "lucas.fernandes@example.com",
            avatar: null,
            password: "lucas321",
            phone_number: "71922221111",
            role: "user",
            cpf: "67890123456",
            verified: true,
            address: {
                street: "Rua Bahia",
                number: "90",
                city: "Salvador",
                cep: "40020110",
                state: "BA",
            },
        },
        {
            name: "Fernanda Lima",
            email: "fernanda.lima@example.com",
            avatar: null,
            password: "fernanda123",
            phone_number: "81911110000",
            role: "user",
            cpf: "78901234567",
            verified: false,
            address: {
                street: "Rua Recife",
                number: "45",
                city: "Recife",
                cep: "50030020",
                state: "PE",
            },
        },
        {
            name: "Gabriel Costa",
            email: "gabriel.costa@example.com",
            avatar: null,
            password: "gabriel123",
            phone_number: "31900009999",
            role: "admin",
            cpf: "89012345678",
            verified: true,
            address: {
                street: "Rua Ouro Preto",
                number: "12",
                city: "Belo Horizonte",
                cep: "30120090",
                state: "MG",
            },
        },
    ]);
    console.log("✅ Users seed executed");
};